tripcore/inventory/urls.py
from django.urls import path
from inventory import views as iviews

urlpatterns = [
    path('', iviews.inventory_home, name='trip_inventory-home'),
    path('company/', iviews.company, name='trip_inventory-company'),
    path('out/', iviews.out, name='trip_inventory-out'),
    path('personal/', iviews.personal, name='trip_inventory-personal'),

    # add views for simpleisbetter... dynamic dropdown method
    path('fixture/', iviews.FixtureListView.as_view(), name='fixture-list'),
    path('fixture/add/', iviews.FixtureCreateView.as_view(), name='fixture-add'),
    path('fixture/<int:pk>/', iviews.FixtureUpdateView.as_view(),
         name='fixture_update'),
    path('ajax/load-fixture-types/', iviews.load_fixture_types,
         name='ajax_load_fixture_types'),
    path('ajax/load-source-types/', iviews.load_source_types,
         name='ajax_load_source_types'),
]

tripcore/users/urls.py
from django.urls import path
from users import views as uviews

urlpatterns = [
    path('', uviews.users_home, name='trip_users-home'),
]

tripcore/inventory/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models
from django import forms


# add classes per https://simpleisbetterthancomplex.com/tutorial/2018/01/29/how-to-implement-dependent-or-chained-dropdown-list-with-django.html


class Source(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Source_Type(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Fixture_Type(models.Model):
    name = models.CharField(max_length=100)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Fixture(models.Model):
    # change to foreign key of users?
    # owner_id = user.id  #must be logged in to create
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    # owner = models.CharField(max_length=100)
    date_added = models.DateTimeField(default=timezone.now)
    last_rented = models.DateTimeField(default=None)
    last_sickbay = models.DateTimeField(default=None)
    last_service = models.TextField()
    manufacturer = models.ForeignKey(
        Manufacturer, on_delete=models.SET_NULL, null=True)
    fixture_type = models.ForeignKey(
        Fixture_Type, on_delete=models.SET_NULL, null=True)
    # model = models.CharField(max_length=100)
    # manufacturer = models.CharField(max_length=100)
    source = models.ForeignKey(Source, on_delete=models.SET_NULL, null=True)
    source_type = models.ForeignKey(
        Source_Type, on_delete=models.SET_NULL, null=True)
    # source = models.CharField(max_length=20, choices=SOURCE_CHOICES, default='conventional')
    # kind = get_kind(source)
    # kind = models.CharField(max_length=20, choices=choose_source(source) or SELECT_SOURCE, default = 'select_source')
    # source = forms.CharField(max_length=15, label='Source:', widget = forms.Select(choices=SOURCE_CHOICES))
    # kind = forms.CharField(max_length=50, label='Source Kind', widget=forms.Select(choices=choose_source(source)), default='conventional')

    def __str__(self):
        return ' '.join([self.manufacturer, self.fixture_type])


class Projector(Fixture):
    pass


class Hardware(Fixture):
    pass

    # def get_absolute_url(self):
    #     return reverse('fixture-list', kwargs={'pk': self.pk})


# class LED(BASE):
#     source = models.CharField(max_length=20)
#     kind = models.CharField(max_length=20)

# class LED_Par(LED):
#     pass

# class LED_Strip(LED):
#     pass

# class LED_Leko(LED):
#     pas

# class Conventional(BASE):
#     source = models.CharField(max_length=20)
#     kind = models.CharField(max_length=20)

# class Parcan(Conventional):
#     pass

# class Leko(Conventional):
#     pass

# class Strip(Conventional):
#     pass

# class Fresnel(Conventional):
#     pass

# class Mover(BASE):
#    source = models.CharField(max_length=20)
#    kind = models.CharField(max_length=20)

# class LED_Mover(Mover):
#     pass

# class Lamp_Mover(Mover):
#     pass


# def choose_source(source):
#     if source == 'led':
#         return LED_KIND_CHOICES
#     elif source == 'conventional':
#         return CONVENTIONAL_KIND_CHOICES
#     elif source == 'mover':
#         return MOVER_KIND_CHOICES
#     else:
#         print('Invalid choice')
#         # raise ValueError


# SOURCE_CHOICES = (
#     ('led', 'LED'),
#     ('conventional', "Conventional"),
#     ('mover', 'Mover')
# )

# LED_KIND_CHOICES = (
#     ('rgb', 'RGB'),
#     ('rgba', 'RGBA'),
#     ('rgbw', 'RGBW'),
#     ('rgbaw', 'RGBAW'),
#     ('rgbawuv', 'RGBAWUV'),
#     ('other', 'Other'),
# )
# CONVENTIONAL_KIND_CHOICES = (
#     ('500', '500'),
#     ('575', '575'),
#     ('750', '750'),
#     ('1_000', '1_000'),
# )

# MOVER_KIND_CHOICES = (
#     ('led_mover', 'LED Mover'),
#     ('lamp_mover', 'Lamped Mover'),
# )

# SELECT_SOURCE = ('select_source', 'Select Source')


# def get_kind(parent_type):
#     if parent_type == 'led':
#         # return LED_KIND_CHOICES
#         return models.CharField(max_length=20, choices=LED_KIND_CHOICES, default='select_source')
#     elif parent_type == 'conventional':
#         # return CONVENTIONAL_KIND_CHOICES
#         return models.CharField(max_length=20, choices=CONVENTIONAL_KIND_CHOICES, default='select_source')
#     elif parent_type == 'mover':
#         # return MOVER_KIND_CHOICES
#         return models.CharField(max_length=20, choices=MOVER_KIND_CHOICES, default='select_source')
#     else:
#         print('Invalid choice')
#         # raise ValueError

tripcore/inventory/forms.py
from django import forms
from .models import Fixture, Fixture_Type, Source, Source_Type, Manufacturer


class FixtureForm(forms.ModelForm):
    class Meta:
        model = Fixture
        fields = ['owner', 'date_added', 'last_rented', 'last_sickbay',
                  'last_service', 'manufacturer', 'fixture_type',
                  'source', 'source_type']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['source_type'].queryset = Source_Type.objects.none()
        self.fields['fixture_type'].queryset = Fixture_Type.objects.none()

        if 'manufacturer' in self.data:
            try:
                manufacturer_id = int(self.data.get('manufacturer'))
                self.fields['fixture_type'].queryset = Fixture_Type.objects.filter(manufacturer_id=manufacturer_id).order_by('name')
            except (TypeError, ValueError):
                pass
        elif self.instance.pk:
            self.fields['fixture_type'].queryset = self.instance.manufacturer.fixture_type_set.order_by('name')

        if 'source' in self.data:
            try:
                source_id = int(self.data.get('source'))
                self.fields['source_type'].queryset = Source_Type.objects.filter(source_id=source_id).order_by('name')
            except (TypeError, ValueError):
                pass
        elif self.instance.pk:
            self.fields['source_type'].queryset = self.instance.source.source_type_set.order_by('name')

tripcore/inventory/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from .models import Fixture, Fixture_Type, Source_Type, Manufacturer, Source
from .forms import FixtureForm

# Create your views here.


def inventory_home(request):
    return render(request, 'inventory/inventory_base.html', {'title': 'Inventory - Home'})


def company(request):
    return render(request, 'inventory/company.html', {'title': 'Inventory - Company'})


def out(request):
    return render(request, 'inventory/out.html', {'title': 'Inventory - Rented Out'})


def personal(request):
    return render(request, 'inventory/personal.html', {'title': 'Inventory - Owned'})

# add changes per simpleisbetter... method


class FixtureListView(ListView):
    model = Fixture
    context_object_name = 'fixtures'


class FixtureCreateView(CreateView):
    model = Fixture
    form_class = FixtureForm
    # fields = ('owner', 'date_added', 'last_rented', 'last_sickbay', 'last_service',
    #           'model', 'manufacturer', 'source', 'kind')
    success_url = reverse_lazy('fixture_list')

    def get_initial(self, *args, **kwargs):
        initial = super(FixtureCreateView, self).get_initial(**kwargs)
        initial['title'] = 'Add Fixture'
        return initial


class FixtureUpdateView(UpdateView):
    model = Fixture
    form_class = FixtureForm
    # fields = ('owner', 'date_added', 'last_rented', 'last_sickbay', 'last_service',
    #           'model', 'manufacturer', 'source', 'kind')
    success_url = reverse_lazy('fixture_list')


def load_source_types(request):
    source_id = request.GET.get('source')
    source_types = Source_Type.objects.filter(
        source_id=source_id).order_by('name')
    return render(request, 'inventory/source_type_dropdown_options.html', {'source_types': source_types})


def load_fixture_types(request):
    manufacturer_id = request.GET.get('manufacturer')
    fixture_types = Fixture_Type.objects.filter(
        manufacturer_id=manufacturer_id).order_by('name')
    return render(request, 'inventory/fixture_type_dropdown_options.html', {'fixture_types': fixture_types})

tripcore/inventory/templates/inventory/company.html
{% extends 'inventory/inventory_base.html' %}
{% block  content %}
    <p>This is the company.html</p>
    <p>This is for things you have access to rent</p>
{% endblock content %}

{% comment %} things you have access to rent {% endcomment %}

tripcore/inventory/templates/inventory/fixture_form.html
{% extends 'inventory/inventory_base.html' %}
{% load crispy_forms_tags %}
{% block  content %}
    <p>This is the fixture_form.html</p>
    <p>This is where to add new items to inventory.</p>

    <h2>Fixture Form</h2>

    <form method="post" id="fixtureForm" data-source_types-url="{% url 'ajax_load_source_types' %}" data-fixture_types-url="{% url 'ajax_load_fixture_types' %}" novalidate>
        {% comment %} {% csrf_token %} {% endcomment %}
        <table>
            {{ form|crispy }}
        </table>
        <button type="submit">Save</button>
        <a href="{% url 'fixture-list' %}">Nevermind</a>
    </form>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    {% comment %} <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> {% endcomment %}
    <script>
        $("#id_manufacturer").change(function () {
        
        var url = $("#fixtureForm").attr("data-fixture_types-url");  // get the url of the `load_cities` view
        var manufacturerId = $(this).val();  // get the selected country ID from the HTML input
        console.log( $(this).val() );
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                data: {
                    'manufacturer': manufacturerId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_fixture_type").html(data);  // replace the contents of the city input with the data that came from the server
                }
            });
        });
    </script>
    <script>
        $("#id_source").change(function () {
        var url = $("#fixtureForm").attr("data-source_types-url");  // get the url of the `load_cities` view
        var sourceId = $(this).val();  // get the selected country ID from the HTML input
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                data: {
                    'source': sourceId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_source_type").html(data);  // replace the contents of the city input with the data that came from the server
                }
            });
        });
    </script>



{% endblock content %}

tripcore/inventory/templates/inventory/fixture_list.html
{% extends 'inventory/inventory_base.html' %}
{% block  content %}
    <p>This is the fixture_list.html</p>
    <p>This is a landing page for all fixture actions</p>
    <h2>Fixture Form</h2>
    <form method="post" novalidate>
        {% comment %} {% csrf_token %} {% endcomment %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Save</button>
        <a href="{% url 'fixture-list' %}">Nevermind</a>
    </form>
{% endblock content %}

{% comment %} things you have access to rent {% endcomment %}

tripcore/inventory/templates/inventory/fixture_type_dropdown_options.html
<option value="">---------</option>
{% for fixture_type in fixture_types %}
<option value="{{ fixture_type.pk }}">{{ fixture_type.name }}</option>
{% endfor %}

tripcore/inventory/templates/inventory/inventory_base.html
{% extends 'landing/trip_base.html' %}
{% block  content %}
    <p>This is the Inventory base</p>
    <ul>
        <li><a href="{% url 'trip_inventory-company' %}">Company</a></li>
        <li><a href="{% url 'trip_inventory-out' %}">Rented to You</a></li>
        <li><a href="{% url 'trip_inventory-personal' %}">Personally Owned</a></li>
    </ul>
{% endblock content %}
{% comment %} 

extends trip_base.html

display user info similar to rental home {% endcomment %}

tripcore/inventory/templates/inventory/kind_dropdown_options.html
<option value="">---------</option>
{% for kind in kinds %}
<option value="{{ kind.pk }}">{{ kind.name }}</option>
{% endfor %}

tripcore/inventory/templates/inventory/out.html
{% extends 'inventory/inventory_base.html' %}
{% block  content %}
    <p>This is the out.html</p>
    <p>This is for things checked out to you</p>
{% endblock content %}

tripcore/inventory/templates/inventory/personal.html
{% extends 'inventory/inventory_base.html' %}
{% block  content %}
    <p>This is the personal.html</p>
    <p>This is for things you personally own</p>
{% endblock content %}

tripcore/inventory/templates/inventory/source_type_dropdown_options.html
<option value="">---------</option>
{% for source_type in source_types %}
<option value="{{ source_type.pk }}">{{ source_type.name }}</option>
{% endfor %}